apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: juice-shop
spec:
  host: app-20-232-62-166.nip.io
  tls:
    secret: juice-shop-secret
  policies:
  - name: nap-policy
  ingressClassName: vini-nginx-ingress  
  upstreams:
  - name: juice-shop
    service: juice-shop-svc
    port: 80
  routes:
  - path: /
    action:
      proxy: 
        upstream: juice-shop
        requestHeaders:
          pass: true
        responseHeaders:
  hide:
    - Access-Control-Allow-Origin
    - Feature-Policy
  add:
    - name: Access-Control-Allow-Credentials
      value: "true"
    - name: Access-Control-Allow-Origin
      value: CHANGE_THIS_TO_YOUR_NGINX_SERVICE_URL
    - name: Content-Security-Policy
      value: default-src 'self'; script-src 'self' 'unsafe-inline' cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com
    - name: Permissions-Policy
      value: payment 'self'


